services:
  db:
    image: mysql:8.0
    container_name: lp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  redis:
    image: redis:alpine
    container_name: lp_redis
    restart: always
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - wp_network

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wp
    image: wordpress:latest
    container_name: lp_wp
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_TABLE_PREFIX: wp_
      WP_REDIS_HOST: redis
      WP_REDIS_PORT: 6379
      WORDPRESS_EXTRA_CONFIG: |
        define('DISALLOW_FILE_EDIT', true);
        define('WP_DEBUG', false);
        define('WP_DEBUG_DISPLAY', false);
        define('FORCE_SSL_ADMIN', true);

        /* Redis */
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379); // 'redis:6379'
        define('WP_REDIS_SELECTIVE_FLUSH', true);
        define( 'WP_REDIS_MAXTTL', 86400 );
      ENV: prod
    volumes:
      # wp-content (themes, uploads, plugins)
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      # max file size definition
      - ./wp-content/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      # robots txt
      - ./wp-content/robots.txt:/var/www/html/robots.txt
    networks:
      - wp_network

  nginx:
      image: nginx:alpine
      container_name: lp_nginx
      restart: always
      depends_on:
        - wordpress
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
        - /etc/letsencrypt:/etc/letsencrypt:ro
        - nginx_cache:/var/cache/nginx
      networks:
        - wp_network

volumes:
  db_data:
  nginx_cache:
  redis_data:

networks:
  wp_network:
    driver: bridge